services:
  - type: web
    name: image-vid-compressor-bot
    runtime: python
    pythonVersion: "3.12.8"  # <--- Add this exact line right here
    buildCommand: apt-get update && apt-get install -y ffmpeg && pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: BOT_TOKEN
        sync: false
