import os
from telegram import Update
from telegram.ext import ContextTypes
from utils.config import MAX_VIDEO_SIZE, DOWNLOAD_DIR, OUTPUT_DIR
from utils.logger import logger
from services.queue_manager import queue_manager
from services.video_compressor import compress_video_file
from services.database import log_history
from keyboards.inline import get_compression_keyboard

async def video_file_receiver(update: Update, context: ContextTypes.DEFAULT_TYPE):
    msg = update.message
    video_file = msg.video or msg.animation or (msg.document if msg.document and msg.document.mime_type.startswith("video/") else None)
    
    if not video_file:
        await msg.reply_text("❌ Media item structure did not pass video signature checking.")
        return
        
    if video_file.file_size > MAX_VIDEO_SIZE:
        await msg.reply_text("⚠️ File footprint breaches max constraints boundaries (250MB).")
        return
        
    context.user_data["pending_file_id"] = video_file.file_id
    context.user_data["pending_file_type"] = "video"
    context.user_data["pending_filename"] = getattr(video_file, "file_name", "video.mp4")
    
    await msg.reply_text(
        f"📊 *Video Asset Loaded*\n\n"
        f"• Dimensions Weight: {video_file.file_size / (1024*1024):.2f} MB\n\n"
        f"Select requested operational compression algorithm profiles:",
        parse_mode="Markdown",
        reply_markup=get_compression_keyboard("video")
    )

async def video_processing_pipeline(update: Update, context: ContextTypes.DEFAULT_TYPE, level: str):
    query = update.callback_query
    user_id = query.from_user.id
    
    file_id = context.user_data.get("pending_file_id")
    filename = context.user_data.get("pending_filename", "video.mp4")
    
    if not file_id:
        await query.message.reply_text("❌ Operational context frame dropped. Re-upload object media infrastructure.")
        return
        
    status_msg = await query.message.reply_text("⏳ Processing queue registration in progress... awaiting slot allocation.")
    await queue_manager.acquire(user_id)
    
    try:
        await status_msg.edit_text("⚡ Downloading video streaming file segments...")
        tg_file = await context.bot.get_file(file_id)
        
        in_path = os.path.join(DOWNLOAD_DIR, f"{user_id}_{file_id}_{filename}")
        out_path = os.path.join(OUTPUT_DIR, f"compressed_{user_id}_{file_id}.mp4")
        
        await tg_file.download_to_drive(in_path)
        await status_msg.edit_text("⚙️ Invoking structural FFmpeg codec transformation chains... (This may take some time)")
        
        success = compress_video_file(in_path, out_path, level)
        
        if success and os.path.exists(out_path):
            await status_msg.edit_text("📤 Dispatching complete file streams to recipient core storage...")
            orig_size = os.path.getsize(in_path)
            comp_size = os.path.getsize(out_path)
            saved_pct = ((orig_size - comp_size) / orig_size) * 100
            
            with open(out_path, "rb") as delivery_file:
                await query.message.reply_video(
                    video=delivery_file,
                    caption=(
                        "✅ *Video Multi-pass Transcode Pipeline Finished.*\n\n"
                        f"• Footprint Delta: {orig_size/(1024*1024):.2f} MB → {comp_size/(1024*1024):.2f} MB\n"
                        f"• Stream Reduction Efficiency: *{saved_pct:.1f}%*"
                    ),
                    parse_mode="Markdown"
                )
            log_history(user_id, filename, orig_size, comp_size)
        else:
            await query.message.reply_text("❌ Non-zero code exception exit generated by native multi-pass codecs.")
            
        for p in (in_path, out_path):
            if os.path.exists(p): os.remove(p)
            
    except Exception as e:
        logger.error(f"Video execution context crash tracking: {e}")
        await query.message.reply_text("💥 An exceptional runtime breakdown closed the processing workspace streams.")
    finally:
        queue_manager.release(user_id)
        await status_msg.delete()
